// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pm/dso.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Dso struct {
	Idx     string `protobuf:"bytes,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Creator string `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Dso) Reset()         { *m = Dso{} }
func (m *Dso) String() string { return proto.CompactTextString(m) }
func (*Dso) ProtoMessage()    {}
func (*Dso) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1422b1531930b19, []int{0}
}
func (m *Dso) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Dso) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Dso.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Dso) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dso.Merge(m, src)
}
func (m *Dso) XXX_Size() int {
	return m.Size()
}
func (m *Dso) XXX_DiscardUnknown() {
	xxx_messageInfo_Dso.DiscardUnknown(m)
}

var xxx_messageInfo_Dso proto.InternalMessageInfo

func (m *Dso) GetIdx() string {
	if m != nil {
		return m.Idx
	}
	return ""
}

func (m *Dso) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Dso) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Dso)(nil), "supsidacdisaac.pm.pm.Dso")
}

func init() { proto.RegisterFile("pm/dso.proto", fileDescriptor_a1422b1531930b19) }

var fileDescriptor_a1422b1531930b19 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xa1, 0x4e, 0xc6, 0x30,
	0x14, 0x85, 0x57, 0x96, 0x40, 0x68, 0x10, 0x64, 0x99, 0x68, 0x10, 0x0d, 0x41, 0x61, 0xd6, 0x0a,
	0x04, 0x9e, 0xe0, 0x50, 0x20, 0x71, 0x5d, 0xbb, 0x8c, 0x8a, 0xe6, 0xde, 0xf4, 0x76, 0xc9, 0xf6,
	0x16, 0x3c, 0x16, 0x72, 0x12, 0x49, 0xb6, 0x17, 0x21, 0xed, 0xfe, 0xdf, 0xdc, 0x9c, 0x73, 0xcf,
	0x27, 0x3e, 0x7e, 0x83, 0x41, 0x3b, 0x02, 0x85, 0x11, 0x12, 0x34, 0x2d, 0x4d, 0x48, 0xde, 0x19,
	0xeb, 0x3c, 0x19, 0x63, 0x15, 0x06, 0x85, 0xe1, 0xae, 0x1d, 0x61, 0x84, 0x02, 0xe8, 0x9c, 0x0e,
	0xf6, 0xe1, 0x8d, 0xd7, 0xaf, 0x04, 0xcd, 0x2d, 0xaf, 0xbd, 0x9b, 0x05, 0xbb, 0x67, 0x8f, 0xd7,
	0x1f, 0x39, 0x36, 0x82, 0x5f, 0x19, 0xe7, 0xe2, 0x40, 0x24, 0x2e, 0xca, 0xf7, 0x5c, 0xf3, 0x62,
	0xe3, 0x60, 0x12, 0x44, 0x51, 0x1f, 0xcb, 0xa9, 0xbe, 0xbc, 0xff, 0x6c, 0x92, 0xad, 0x9b, 0x64,
	0x7f, 0x9b, 0x64, 0xdf, 0xbb, 0xac, 0xd6, 0x5d, 0x56, 0xbf, 0xbb, 0xac, 0x3e, 0x9f, 0x47, 0x9f,
	0xbe, 0xa6, 0x5e, 0x59, 0x08, 0xba, 0xd8, 0x75, 0x59, 0xaf, 0x2b, 0x7e, 0x1a, 0x4d, 0xf4, 0x69,
	0xe9, 0x2c, 0x50, 0x00, 0xd2, 0x18, 0xf4, 0x9c, 0x4f, 0x5a, 0x70, 0xa0, 0xfe, 0xb2, 0x68, 0x3e,
	0xfd, 0x07, 0x00, 0x00, 0xff, 0xff, 0xad, 0xaa, 0x61, 0xff, 0xe2, 0x00, 0x00, 0x00,
}

func (m *Dso) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Dso) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Dso) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintDso(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintDso(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Idx) > 0 {
		i -= len(m.Idx)
		copy(dAtA[i:], m.Idx)
		i = encodeVarintDso(dAtA, i, uint64(len(m.Idx)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDso(dAtA []byte, offset int, v uint64) int {
	offset -= sovDso(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Dso) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Idx)
	if l > 0 {
		n += 1 + l + sovDso(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovDso(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovDso(uint64(l))
	}
	return n
}

func sovDso(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDso(x uint64) (n int) {
	return sovDso(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Dso) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDso
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Dso: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Dso: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Idx", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDso
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDso
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDso
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Idx = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDso
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDso
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDso
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDso
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDso
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDso
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDso(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDso
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDso(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDso
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDso
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDso
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDso
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDso
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDso
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDso        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDso          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDso = fmt.Errorf("proto: unexpected end of group")
)
