// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pm/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the pm module's genesis state.
type GenesisState struct {
	Dso                *Dso             `protobuf:"bytes,1,opt,name=dso,proto3" json:"dso,omitempty"`
	Aggregator         *Aggregator      `protobuf:"bytes,2,opt,name=aggregator,proto3" json:"aggregator,omitempty"`
	PlayerList         []Player         `protobuf:"bytes,3,rep,name=playerList,proto3" json:"playerList"`
	LemList            []Lem            `protobuf:"bytes,4,rep,name=lemList,proto3" json:"lemList"`
	LemMeasureList     []LemMeasure     `protobuf:"bytes,5,rep,name=lemMeasureList,proto3" json:"lemMeasureList"`
	SlaList            []Sla            `protobuf:"bytes,6,rep,name=slaList,proto3" json:"slaList"`
	KpiList            []Kpi            `protobuf:"bytes,7,rep,name=kpiList,proto3" json:"kpiList"`
	KpiMeasureList     []KpiMeasure     `protobuf:"bytes,8,rep,name=kpiMeasureList,proto3" json:"kpiMeasureList"`
	LemDatasetList     []LemDataset     `protobuf:"bytes,9,rep,name=lemDatasetList,proto3" json:"lemDatasetList"`
	DefaultLemParsList []DefaultLemPars `protobuf:"bytes,10,rep,name=defaultLemParsList,proto3" json:"defaultLemParsList"`
	MarketOperator     *MarketOperator  `protobuf:"bytes,11,opt,name=marketOperator,proto3" json:"marketOperator,omitempty"`
	GridStateList      []GridState      `protobuf:"bytes,12,rep,name=gridStateList,proto3" json:"gridStateList"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec31e9358cfa321, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetDso() *Dso {
	if m != nil {
		return m.Dso
	}
	return nil
}

func (m *GenesisState) GetAggregator() *Aggregator {
	if m != nil {
		return m.Aggregator
	}
	return nil
}

func (m *GenesisState) GetPlayerList() []Player {
	if m != nil {
		return m.PlayerList
	}
	return nil
}

func (m *GenesisState) GetLemList() []Lem {
	if m != nil {
		return m.LemList
	}
	return nil
}

func (m *GenesisState) GetLemMeasureList() []LemMeasure {
	if m != nil {
		return m.LemMeasureList
	}
	return nil
}

func (m *GenesisState) GetSlaList() []Sla {
	if m != nil {
		return m.SlaList
	}
	return nil
}

func (m *GenesisState) GetKpiList() []Kpi {
	if m != nil {
		return m.KpiList
	}
	return nil
}

func (m *GenesisState) GetKpiMeasureList() []KpiMeasure {
	if m != nil {
		return m.KpiMeasureList
	}
	return nil
}

func (m *GenesisState) GetLemDatasetList() []LemDataset {
	if m != nil {
		return m.LemDatasetList
	}
	return nil
}

func (m *GenesisState) GetDefaultLemParsList() []DefaultLemPars {
	if m != nil {
		return m.DefaultLemParsList
	}
	return nil
}

func (m *GenesisState) GetMarketOperator() *MarketOperator {
	if m != nil {
		return m.MarketOperator
	}
	return nil
}

func (m *GenesisState) GetGridStateList() []GridState {
	if m != nil {
		return m.GridStateList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "supsidacdisaac.pm.pm.GenesisState")
}

func init() { proto.RegisterFile("pm/genesis.proto", fileDescriptor_fec31e9358cfa321) }

var fileDescriptor_fec31e9358cfa321 = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x1b, 0x3a, 0x3a, 0x70, 0xcb, 0x40, 0x66, 0x87, 0xac, 0x42, 0x59, 0x85, 0x38, 0x4c,
	0x42, 0x8d, 0xa5, 0x71, 0x40, 0xdc, 0xa0, 0x9a, 0xb4, 0x43, 0x3b, 0x18, 0xdd, 0x6d, 0x97, 0xca,
	0x6b, 0x4c, 0xb0, 0x12, 0xe3, 0x27, 0xdb, 0x95, 0xe8, 0xb7, 0xe0, 0x63, 0xed, 0xd8, 0x23, 0x5c,
	0x10, 0x6a, 0xbf, 0x08, 0xb2, 0xe3, 0x94, 0xb4, 0x4a, 0xcb, 0xa5, 0xb2, 0xdd, 0xff, 0xff, 0xa7,
	0xff, 0x7b, 0x79, 0x0f, 0x3d, 0x03, 0x41, 0x52, 0xf6, 0x8d, 0x69, 0xae, 0x63, 0x50, 0xd2, 0x48,
	0x7c, 0xac, 0x67, 0xa0, 0x79, 0x42, 0xa7, 0x09, 0xd7, 0x94, 0x4e, 0x63, 0x10, 0x31, 0x88, 0x6e,
	0x07, 0x04, 0x49, 0xb4, 0x2c, 0x34, 0xdd, 0xe7, 0x20, 0x08, 0x4d, 0x53, 0xc5, 0x52, 0x6a, 0xa4,
	0xf2, 0x8f, 0x4f, 0x41, 0x10, 0xc8, 0xe9, 0x9c, 0x95, 0x0f, 0xd6, 0x93, 0x33, 0xe1, 0x6f, 0xc7,
	0xc5, 0x6d, 0x22, 0x18, 0xd5, 0x33, 0xc5, 0x2a, 0x1a, 0x9d, 0xd3, 0xca, 0x2d, 0x03, 0x5e, 0x71,
	0x64, 0xc0, 0xb7, 0x1c, 0x25, 0x27, 0xa1, 0x86, 0x6a, 0x66, 0xfc, 0xeb, 0x89, 0xcd, 0xc7, 0xbe,
	0xd0, 0x59, 0x6e, 0x26, 0xf6, 0x5f, 0xa0, 0xca, 0x17, 0xd4, 0x0d, 0x41, 0x10, 0x41, 0x55, 0xc6,
	0xcc, 0x44, 0x02, 0x53, 0x95, 0xc4, 0xb6, 0x8c, 0x54, 0xf1, 0x64, 0xa2, 0x0d, 0x35, 0x6b, 0x7e,
	0x2a, 0x53, 0xe9, 0x8e, 0xc4, 0x9e, 0x8a, 0xd7, 0x97, 0xbf, 0x5a, 0xa8, 0x73, 0x59, 0xf4, 0xe9,
	0xc6, 0x8a, 0xf1, 0x6b, 0xd4, 0x4c, 0xb4, 0x0c, 0x83, 0x5e, 0x70, 0xd6, 0x3e, 0x3f, 0x89, 0xeb,
	0x9a, 0x16, 0x5f, 0x68, 0x39, 0xb6, 0x2a, 0xfc, 0x1e, 0xa1, 0x7f, 0xed, 0x0a, 0x1f, 0x38, 0x4f,
	0xaf, 0xde, 0xf3, 0x61, 0xad, 0x1b, 0x57, 0x3c, 0x78, 0x80, 0x50, 0xd1, 0xdb, 0x11, 0xd7, 0x26,
	0x6c, 0xf6, 0x9a, 0x67, 0xed, 0xf3, 0x17, 0xf5, 0x84, 0x6b, 0xa7, 0x1b, 0x1c, 0xdc, 0xff, 0x3e,
	0x6d, 0x8c, 0x2b, 0x2e, 0xfc, 0x0e, 0x1d, 0xe6, 0x4c, 0x38, 0xc0, 0x81, 0x03, 0xec, 0x88, 0x3d,
	0x62, 0xc2, 0xbb, 0x4b, 0x3d, 0xfe, 0x88, 0x8e, 0x72, 0x26, 0xae, 0x8a, 0x0f, 0xe1, 0x08, 0x0f,
	0x1d, 0xa1, 0xb7, 0x93, 0xe0, 0xb5, 0x1e, 0xb4, 0xe5, 0xb6, 0x51, 0x74, 0x4e, 0x1d, 0xa8, 0xb5,
	0x2f, 0xca, 0x4d, 0x4e, 0xcb, 0x28, 0x5e, 0x6f, 0xad, 0x19, 0x70, 0x67, 0x3d, 0xdc, 0x67, 0x1d,
	0x02, 0x2f, 0xad, 0x5e, 0x6f, 0xab, 0xc8, 0x80, 0x57, 0xab, 0x78, 0xb4, 0xaf, 0x8a, 0xe1, 0x5a,
	0x5b, 0x56, 0xb1, 0xe9, 0xf6, 0x5d, 0xb9, 0x28, 0x06, 0xd1, 0xf1, 0x1e, 0xff, 0xa7, 0x2b, 0x5e,
	0x5b, 0xe9, 0x4a, 0xc5, 0x8d, 0x6f, 0x11, 0xf6, 0x33, 0x3c, 0x62, 0xe2, 0x9a, 0x2a, 0xed, 0x98,
	0xc8, 0x31, 0x5f, 0xed, 0x18, 0xb1, 0x0d, 0xbd, 0xe7, 0xd6, 0x50, 0xf0, 0x08, 0x1d, 0x15, 0x4b,
	0xf0, 0xc9, 0xef, 0x40, 0xd8, 0x76, 0x63, 0xb8, 0x83, 0x7b, 0xb5, 0xa1, 0x1d, 0x6f, 0x79, 0xf1,
	0x10, 0x3d, 0xb1, 0x8b, 0xe3, 0x56, 0xc1, 0x85, 0xec, 0xb8, 0x90, 0xa7, 0xf5, 0xb0, 0xcb, 0x52,
	0xea, 0xf3, 0x6d, 0x7a, 0x07, 0x9f, 0xef, 0x97, 0x51, 0xb0, 0x58, 0x46, 0xc1, 0x9f, 0x65, 0x14,
	0xfc, 0x58, 0x45, 0x8d, 0xc5, 0x2a, 0x6a, 0xfc, 0x5c, 0x45, 0x8d, 0xdb, 0xb7, 0x29, 0x37, 0x5f,
	0x67, 0x77, 0xf1, 0x54, 0x0a, 0xe2, 0xc8, 0x7d, 0x8b, 0xee, 0x3b, 0x36, 0x01, 0xaa, 0xb8, 0x99,
	0xf7, 0xa7, 0x52, 0x0b, 0xa9, 0x09, 0x08, 0xf2, 0xdd, 0xfe, 0x98, 0x39, 0x30, 0x7d, 0xd7, 0x72,
	0x5b, 0xfb, 0xe6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0xe4, 0x6c, 0x32, 0xdf, 0x04, 0x00,
	0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GridStateList) > 0 {
		for iNdEx := len(m.GridStateList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GridStateList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if m.MarketOperator != nil {
		{
			size, err := m.MarketOperator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if len(m.DefaultLemParsList) > 0 {
		for iNdEx := len(m.DefaultLemParsList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DefaultLemParsList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.LemDatasetList) > 0 {
		for iNdEx := len(m.LemDatasetList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LemDatasetList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.KpiMeasureList) > 0 {
		for iNdEx := len(m.KpiMeasureList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.KpiMeasureList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.KpiList) > 0 {
		for iNdEx := len(m.KpiList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.KpiList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.SlaList) > 0 {
		for iNdEx := len(m.SlaList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SlaList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.LemMeasureList) > 0 {
		for iNdEx := len(m.LemMeasureList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LemMeasureList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.LemList) > 0 {
		for iNdEx := len(m.LemList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LemList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.PlayerList) > 0 {
		for iNdEx := len(m.PlayerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PlayerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Aggregator != nil {
		{
			size, err := m.Aggregator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Dso != nil {
		{
			size, err := m.Dso.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Dso != nil {
		l = m.Dso.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Aggregator != nil {
		l = m.Aggregator.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.PlayerList) > 0 {
		for _, e := range m.PlayerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.LemList) > 0 {
		for _, e := range m.LemList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.LemMeasureList) > 0 {
		for _, e := range m.LemMeasureList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SlaList) > 0 {
		for _, e := range m.SlaList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.KpiList) > 0 {
		for _, e := range m.KpiList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.KpiMeasureList) > 0 {
		for _, e := range m.KpiMeasureList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.LemDatasetList) > 0 {
		for _, e := range m.LemDatasetList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.DefaultLemParsList) > 0 {
		for _, e := range m.DefaultLemParsList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.MarketOperator != nil {
		l = m.MarketOperator.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.GridStateList) > 0 {
		for _, e := range m.GridStateList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dso", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Dso == nil {
				m.Dso = &Dso{}
			}
			if err := m.Dso.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Aggregator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Aggregator == nil {
				m.Aggregator = &Aggregator{}
			}
			if err := m.Aggregator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlayerList = append(m.PlayerList, Player{})
			if err := m.PlayerList[len(m.PlayerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LemList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LemList = append(m.LemList, Lem{})
			if err := m.LemList[len(m.LemList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LemMeasureList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LemMeasureList = append(m.LemMeasureList, LemMeasure{})
			if err := m.LemMeasureList[len(m.LemMeasureList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlaList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlaList = append(m.SlaList, Sla{})
			if err := m.SlaList[len(m.SlaList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KpiList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KpiList = append(m.KpiList, Kpi{})
			if err := m.KpiList[len(m.KpiList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KpiMeasureList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KpiMeasureList = append(m.KpiMeasureList, KpiMeasure{})
			if err := m.KpiMeasureList[len(m.KpiMeasureList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LemDatasetList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LemDatasetList = append(m.LemDatasetList, LemDataset{})
			if err := m.LemDatasetList[len(m.LemDatasetList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultLemParsList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultLemParsList = append(m.DefaultLemParsList, DefaultLemPars{})
			if err := m.DefaultLemParsList[len(m.DefaultLemParsList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketOperator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MarketOperator == nil {
				m.MarketOperator = &MarketOperator{}
			}
			if err := m.MarketOperator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GridStateList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GridStateList = append(m.GridStateList, GridState{})
			if err := m.GridStateList[len(m.GridStateList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
